config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#index'
  resources :homes,only: [:inedx]
  resources :cafes,only: [:index]
  resources :reservations,only: [:index]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cafes_controller.rb
class CafesController < ApplicationController
  def index
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cafes_helper.rb
module CafesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/cafes/_Ctop.html.haml
.main
  .top
    .top__contents
      .top__contents__title
        Cafe OFANA
      .top__contents__words
        %h1#menu-list
          +メニュー
          %p.menu
            Morning
          %p.menu
            Lunch
          %p.menu
            Dinner
        %h1#time
          +営業時間
          %p.hour
            月-金 / 9:00 – 21:00
          %p.hour
            土日祝日 / 8:00 – 22:00

        %h1#reserv
          +ご予約
          %p.phone
            電話予約 050-0915-0902 
          %p.net
            =link_to 'インターネット予約', reservations_path, class: "words"
        %h1#info
          +インフォメーション
          %p.store
            駐車場 10台
          %p.store
            ペット: テラスのみ入場可
          %p.store
            ※但し、盲導犬、聴導犬、介助犬は入店可能
      .top__contents__address
        %p 
          〒192-8577 東京都
        %p 
          八王子市 丹木町1丁目236

        %p 
          TEL 050-0915-0902 


    .top__photo
      <img src="/topics/cafe2.jpg" alt=" " class="top__photo" />
      <img src="/topics/cafe1.jpg" alt=" " class="top__photo" />

app/views/cafes/_header.html.haml
.header
  .logo
    <img src="/logo.jpg" alt=" " class="logo" />


  .buttom  
    .list
      %p
        =link_to 'Home', root_path, class: "list"
      %p 
        =link_to 'Info', 'http://www.google.co.jp/', class: "list"
      %p
        =link_to 'Cafe', cafes_path, class: "list"
      %p
        =link_to 'Online Shop', 'http://www.google.co.jp/', class: "list"
      %p
        =link_to 'Travel', 'http://www.google.co.jp/', class: "list"
      %p
        =link_to 'Contact', 'http://www.google.co.jp/', class: "list"

    .icon
      = link_to "https://www.facebook.com/fanamby.razafimanantena/", class: "icon" do
        = icon('fab', 'facebook',  class: "icon")
      = link_to "https://twitter.com/fana0915", class: "icon" do
        = icon('fab', 'twitter',  class: "icon")
      = link_to "https://www.instagram.com/fana0902/", class: "icon" do
        = icon('fab', 'instagram',  class: "icon")

app/views/cafes/index.html.haml
.wrapper
  = render "header"
  = render "Ctop"

app/views/homes/_header.html.haml
.header
  .logo
    logo

  .buttom  
    .list
      %p
        =link_to 'Home', root_path , class: "list"
      %p 
        =link_to 'Info', 'http://www.google.co.jp/', class: "list"
      %p
        =link_to 'Cafe', cafes_path, class: "list"
      %p
        =link_to 'Online Shop', 'http://www.google.co.jp/', class: "list"
      %p
        =link_to 'Travel', 'http://www.google.co.jp/', class: "list"
      %p
        =link_to 'Contact', 'http://www.google.co.jp/', class: "list"

    .icon
      = link_to "https://www.facebook.com/fanamby.razafimanantena/", class: "icon" do
        = icon('fab', 'facebook',  class: "icon")
      = link_to "https://twitter.com/fana0915", class: "icon" do
        = icon('fab', 'twitter',  class: "icon")
      = link_to "https://www.instagram.com/fana0902/", class: "icon" do
        = icon('fab', 'instagram',  class: "icon")

app/views/homes/_top.html.haml
.main
  .introduction
    .introduction__content
      .introduction__content__title
        %p 
          日本の美しい素材と、
        %p 
          マダガスカルの大自然が生んだ
        %p 
          幻想的な空間

      .introduction__content__words
        %p 
          四季とともに変化する日本の恵
        %p 
          地球の歴史がつりあげたマダガスカルの景色
        %p 
          大海原にかこまれたこの2つの島の色を
        %p 
          かけあわせた新しい世界。
        %p 
          そんな世界観が楽しめる空間を
        %p 
          どうぞお楽しみください。

    %ul.slider
      %li
        = image_tag "/introduction/mada_image1.jpg", alt: " ", class:"image"
      %li
        = image_tag "/introduction/japan_image2.jpg", alt: " ", class:"image"
      %li
        = image_tag "/introduction/mada_image2.jpg", alt: " ", class:"image"        
      %li
        = image_tag "/introduction/japan_image3.jpg", alt: " ", class:"image"
      %li
        = image_tag "/introduction/mada_image3.jpg", alt: " ", class:"image"  
      %li
        = image_tag "/introduction/japan_image1.jpg", alt: " ", class:"image"

  .menu
    .title
      Topics
    .topics
      .topics__cafe
        = link_to cafes_path do
          <img src="/topics/cafe_image.jpg" alt=" " class="topic" />
        .explanatory
          %p
            現地の美味しさを
          %p
            お届けします。
      
      .topics__shop
        <img src="/topics/shop_image.jpg" alt=" " class="topic" />
        .explanatory
          %p
            大自然を生かした
          %p
            モノつくり

      .topics__travel
        <img src="/topics/travel_image.jpg" alt=" " class="topic" />
        .explanatory      
          %p
            幻想的な世界への
          %p
            ご案内

      .topics__instagram
        = link_to "https://www.instagram.com/fana0902/", class: "topic" do
          <img src="/topics/instagram_image.jpg" alt=" " class="topic" />
        .explanatory
          %p
            日々の様子を
          %p
            写真と共に配信しています。

app/views/homes/index.html.haml
.wrapper
  = render "header"
  = render "top"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title MadaCafe
    %meta{content:"text/html; charset=UTF-8", "http-equiv": "Content-Type"}/
    %meta{content: "width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0", name: "viewport"}
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all'
    %link{ rel: "stylesheet", type: "text/css", href: "//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"}
    = javascript_include_tag 'application'
    %script{ type: "text/javascript", src: "//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"}

  %body{"data-turbolinks" => "false"}
    = yield

app/views/reservations/_header.html.haml
.header
  .logo
    <img src="/logo.jpg" alt=" " class="logo" />

  .buttom  
    .list
      %p
        =link_to 'Home', root_path , class: "list"
      %p 
        =link_to 'Info', 'http://www.google.co.jp/', class: "list"
      %p
        =link_to 'Cafe', cafes_path, class: "list"
      %p
        =link_to 'Online Shop', 'http://www.google.co.jp/', class: "list"
      %p
        =link_to 'Travel', 'http://www.google.co.jp/', class: "list"
      %p
        =link_to 'Contact', 'http://www.google.co.jp/', class: "list"

    .icon
      = link_to "https://www.facebook.com/fanamby.razafimanantena/", class: "icon" do
        = icon('fab', 'facebook',  class: "icon")
      = link_to "https://twitter.com/fana0915", class: "icon" do
        = icon('fab', 'twitter',  class: "icon")
      = link_to "https://www.instagram.com/fana0902/", class: "icon" do
        = icon('fab', 'instagram',  class: "icon")

app/views/reservations/index.html.haml
.wrapper
  = render "header"